// Copyright (c) 2018, 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: contract-testing
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate:
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 4
:page-description: Learn how to implement contract testing to ensure compatibility for Java microservices and Cloud-native applications.
:page-seo-title: Implementing consumer driven contract testing for Java microservices and Cloud-native applications.
:page-seo-description: A getting started tutorial on implementing consumer driven contract testing for Java microservices and Cloud-native applications.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE', 'Contract Testing', 'Consumer Driven Test']
:page-related-guides: ['microshed-testing', 'reactive-service-testing', 'arquillian-managed']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Testing with Consumer Driven Contracts

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to test Java microservices with Consumer Driven Contracts in Open Liberty.

== What you'll learn

With microservices-based architecture, there is a need for robust testing to ensure that microservices that are dependent on one another are able to communicate effectively.
Typically, to prevent multiple points of failures at different integration points, a combination of unit, integration, and end-2-end tests are used.
While unit tests are fast, they are less trustworthy as they run in isolation and usually relies on mock data.

Integration tests address this by testing against real running services. However, they tend to be slow as the tests depend on other microservices and are less reliable as they are prone to changes beyond its control.

Usually, end-to-end tests tend to be more trustworthy as it verifies functionality from the perspective of a user. Nevertheless, it also comes with its challenges; there is usually a GUI component that
is required to perform end-to-end tests and relies on 3rd party software such as Selenium which requires heavy compute time and resources.

Contract testing can be used in order to bridge the gap among the shortcomings of those testing methodologies. Contract testing is a technique for testing an integration point by isolating each application and checking if the
HTTP requests and responses it transmits conform to a shared understanding that is documented in a contract.
It ensures that microservices can communicate with each other.

The two microservices you will interact with are called system and inventory. The system microservice returns the JVM
system properties of its host. The inventory microservice retrieves specific properties from the system microservice. You will
learn how to use the https://docs.pact.io/[Pact^] framework to write contracts for the inventory application that will be verified by
the system application.

=== What is Pact?

Pact is an open source contract testing tool. It is a code-first tool for testing HTTP and message integrations using contract tests.

=== What is Pact Broker?

The pact broker is an application for sharing pact contracts and verification results, and is an important piece for integrating pact into CI/CD pipelines.

== Additional prerequisites

Before you begin, Docker needs to be installed. For installation instructions, refer to the https://docs.docker.com/get-docker/[official Docker documentation^]. You will deploy the pact broker application in a Docker container.

Make sure to start your Docker daemon before you proceed.

[role="command"]
include::{common-includes}/gitclone.adoc[]

Next, start pact broker:
[role='command']
```
docker-compose -f "pact-broker/docker-compose.yml" up -d --build
```

Once the pact broker application is running, you will see:
[role="no_copy"]
```
Creating pact-broker_postgres_1 ... done
Creating pact-broker_pact-broker_1 ... done
```

Navigate to http://localhost:9292/[^] to confirm that you can view the Pact Broker application's UI.

You can refer to the https://docs.pact.io/pact_broker/docker_images/pactfoundation[official Pact Broker documentation^]
for more information about the components of the docker compose file.

== Implementing Pact in Inventory Application

Navigate to the `start` directory to begin.

You can find the starting Java projects in the `start` directory. It is made up of the `system` and `inventory` microservices.
Each microservice lives in its own corresponding directory, `system` and `inventory`.

Navigate to the `inventory` directory.

[role=command]
include::{common-includes}/devmode-lmp33-start.adoc[]

inventory/pom.xml
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/pom.xml[]
----

InventoryPactIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryPactIT.java[]
----

The pact framework provides a [hotspot=pactPlugin file=0]`plugin` that can be added to the build section of the `pom.xml`. It contains the [hotspot=endpoint file=0]`endpoint` URL for the system microservice and the [hotspot=pactDirectory file=0]`location` at which the pact file will be stored. The [hotspot=pactJunit file=0]`pact-jvm-consumer-junit`
dependency provides the base test class for use with Junit to build the unit tests.

[role="code_command hotspot", subs="quotes"]
----
#Replace the inventory pom file.#
`inventory/pom.xml`
----

The `InventoryPactIT` class contains a [hotspot=mockprovider file=2]`mock provider` that mimics the HTTP responses from the system microservice.
The `@Pact` annotation takes the name of the microservice as a parameter. This is useful when testing multiple microservices.

The [hotspot=builder file=2]`RequestResponsePact` method defines the minimal expected response for a specific endpoint also known as an interaction.
For each interaction, the expected request and the response are registered with the mock service using the `@PactVerification` annotation.

The [hotspot=mockTest file=2]`test` sends a real request to the mock provider. The mock provider compares the actual request with the expected request and confirms if the comparison is successful.
Finally, the [hotspot=unitTest file=2]`unit test` confirms that the response is correct.

[role="code_command hotspot file=2", subs="quotes"]
----
#Create the InventoryPactIT.java file.#
`inventory/src/test/java/io/openliberty/guides/inventory/InventoryPactIT.java
----
After you replace the `pom.xml` and create the `InventoryPactIT.java` file, Open Liberty automatically reloads its configuration.

A contract between inventory and system is called a pact. Each pact is a collection of interactions that have been defined in the `InventoryPactIT` class.

Press the `enter/return` key to run the tests and generate the pact file.

When integrating pact in a CI/CD pipeline, the `mvn verify` goal can be used instead to generate the pact file.

The generated pact file is named `Inventory-System.json` and is located in `inventory/target/pacts`. It contains the defined interactions in `.json` format:

[role="no_copy"]
----
{
...
"interactions": [
{
      "description": "a request for os encoding entity",
      "request": {
        "method": "GET",
        "path": "/system/properties/key/os.encoding"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": [
          {
            "os.encoding": "UTF-8"
          }
        ]
      },
      "providerStates": [
        {
          "name": "os.encoding is UTF-8"
        }
      ]
    }
...
  ]
}
----

Now that the pact file has been generated, open a new terminal to publish it to the pact broker using:
[role='command']
```
mvn pact:publish
```

When completed, you should see:
[role="no_copy"]
```
[INFO] --- maven:4.1.0:publish (default-cli) @ inventory ---
Publishing 'Inventory-System.json' with tags 'open-liberty-pact' ... OK
```

== Verifying the Pact in Pact Broker

Refresh the http://localhost:9292/[pact broker webpage^] to verify that a new entry has been added. Note that there is no
timestamp in the `Last verified` column as the pact has not been verified by the system microservice yet.

You can also visit the http://localhost:9292/pacts/provider/System/consumer/Inventory/latest[interactions^] URL for more insights about each interaction that has been created.

A snippet of the page looks similar to:
```
A pact between Inventory and System
Requests from Inventory to System
A request for os encoding entity given os.encoding is UTF-8

A request for the version given version is 1.1

A request to check for the default directory given default directory is true

Interactions
Given os.encoding is UTF-8, upon receiving a request for os encoding entity from Inventory, with

{
  "method": "GET",
  "path": "/system/properties/key/os.encoding"
}
System will respond with:

{
  "status": 200,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": [
    {
      "os.encoding": "UTF-8"
    }
  ]
}
```
== Implementing Pact in System Application

system/pom.xml
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/pom.xml[]
----

SystemBrokerIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemBrokerIT.java[]
----

Navigate to the `system` directory.

Open another command-line session to start Open Liberty in dev mode for the system microservice:
[role=command]
```
mvn liberty:dev
```

After you see the following message, your application server in dev mode is ready:

[role="no_copy"]
----
************************************************************************
*    Liberty is running in dev mode.
----

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the SystemBrokerIT.java file.#
`system/src/test/java/it/io/openliberty/guides/system/SystemBrokerIT.java`
----

[hotspot=pactDependency file=0]`Junit5 pact provider` dependency is used for the system microservice to connect to the pact broker to verify the pact file.
The connection information for the pact broker is provided with the [hotspot=connectionInfo file=1]`@PactBroker` annotation. The dependency also provides a [hotspot=invocation file=1]`JUnit5 Invocation Context Provider` to write pact verification tests that is used with the `@TestTemplate` annotation. This generates a test for each of the interactions.

A system property is set to true for [hotspot=publish file=1]`pact.verifier.publishResults` so that the results are sent to the pact broker after the tests are completed.

The test target is defined on the `PactVerificationContext` to point to the running endpoint of the system microservice.

The `@State` annotation must match the `.given()` parameter that was provided by the inventory test class.

After you create the `SystemBrokerIT.java` file, Open Liberty automatically reloads its configuration.

== Verifying the Contract

Press the `enter/return` key to run the tests to verify the pact file. When integrating pact in a CI/CD pipeline, the `mvn test` goal can be used instead to verify the pact file from the pact broker.

```
...
Verifying a pact between Pact between Inventory (1.0-SNAPSHOT) and System

  Notices:
    1) The pact at http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/XXX is being verified because it matches the following configured selection criterion: latest pact for a consumer version tagged 'open-liberty-pact'

  [from Pact Broker http://localhost:9292/pacts/provider/System/consumer/Inventory/pact-version/XXX]
  Given version is 1.1
  a request for the version
    returns a response which
      has status code 200 (OK)
      has a matching body (OK)
[main] INFO au.com.dius.pact.provider.DefaultVerificationReporter - Published verification result of 'au.com.dius.pact.core.pactbroker.TestResult$Ok@4d84dfe7' for consumer 'Consumer(name=Inventory)'
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.835 s - in it.io.openliberty.guides.system.SystemBrokerIT
...
```
Once you see something similar to the above, refresh the http://localhost:9292/[pact broker webpage^] to confirm that there is now a timestamp in the `Last verified` column.

The pact file created by the inventory microservice has been successfully verified by the system microservice. This ensures that responses from the system microservice actually meets the expectation of the inventory microservice.

== Tearing down the environment

[role=command]
include::{common-includes}/devmode-quit.adoc[]

[role='command']
```
docker-compose -f "pact-broker/docker-compose.yml" down
docker rmi postgres:12
docker rmi pactfoundation/pact-broker:2.62.0.0
docker volume rm pact-broker_postgres-volume
```

== Great work! You're done!

You have implemented contract testing using pact in microservices and verified the contract using the pact broker.

== Related Links

Learn more about the Pact framework.

https://pact.io/[View the Pact website^]

include::{common-includes}/attribution.adoc[subs="attributes"]